xcodebuild -project _SPARTA_ambiBIN_/make/MacOSX/Xcode/sparta_ambiBIN.xcodeproj -alltargets -configuration Release
xcodebuild -project _SPARTA_ambiDEC_/make/MacOSX/Xcode/sparta_ambiDEC.xcodeproj -alltargets -configuration Release
xcodebuild -project _SPARTA_ambiDRC_/make/MacOSX/Xcode/sparta_ambiDRC.xcodeproj -alltargets -configuration Release
xcodebuild -project _SPARTA_ambiENC_/make/MacOSX/Xcode/sparta_ambiENC.xcodeproj -alltargets -configuration Release
xcodebuild -project _SPARTA_array2sh_/make/MacOSX/Xcode/sparta_array2sh.xcodeproj -alltargets -configuration Release
xcodebuild -project _SPARTA_beamformer_/make/MacOSX/Xcode/sparta_beamformer.xcodeproj -alltargets -configuration Release
xcodebuild -project _SPARTA_binauraliser_/make/MacOSX/Xcode/sparta_binauraliser.xcodeproj -alltargets -configuration Release
xcodebuild -project _SPARTA_dirass_/make/MacOSX/Xcode/sparta_dirass.xcodeproj -alltargets -configuration Release
xcodebuild -project _SPARTA_MatrixConv_/make/MacOSX/Xcode/sparta_matrixconv.xcodeproj -alltargets -configuration Release
xcodebuild -project _SPARTA_MultiConv_/make/MacOSX/Xcode/sparta_multiconv.xcodeproj -alltargets -configuration Release
xcodebuild -project _SPARTA_panner_/make/MacOSX/Xcode/sparta_panner.xcodeproj -alltargets -configuration Release
xcodebuild -project _SPARTA_powermap_/make/MacOSX/Xcode/sparta_powermap.xcodeproj -alltargets -configuration Release
xcodebuild -project _SPARTA_rotator_/make/MacOSX/Xcode/sparta_rotator.xcodeproj -alltargets -configuration Release
xcodebuild -project _SPARTA_sldoa_/make/MacOSX/Xcode/sparta_sldoa.xcodeproj -alltargets -configuration Release
